POST http://localhost:3000/api/v1/picture/upload/batch
Content-Type: application/json
Cookie: connect.sid=s%3A3KNZ4UMFz2nKnO3uOPOxjZYKTtIlgNI8.8RfAup365xcl9RKA%2B68NLBY7xaWgSguR8HUsJYdsZm4

{
    "keywords": "美女",
    "count": 10
}
